### ISSUE TITLE
why can't I imported the project to IDEA?

### ISSUE THREAD

**Issue by herofor** [spring-cloud/spring-cloud-zookeeper#100]
Like title description,i use Intellij Idea importing the project,the dependencies won't download whether auto or by hand.

**Comment by marcingrzejszczak** [comment]
I can import the project ;) So maybe you can provide more information? Maybe your internet connection is wrong? Maybe you are behind a firewall? Are you able to build the project with `./mvnw clean install` ? Please be more specific

**Comment by marcingrzejszczak** [comment]
Ping @herofor ?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
