### ISSUE TITLE
Add option to disable ZookeeperDiscoveryHealthIndicator with properties.

### ISSUE THREAD

**Issue by zdlgrj** [spring-cloud/spring-cloud-zookeeper#101]
I need to disable the ZookeeperDiscoveryHealthIndicator within a springboot-based application. Our application has its /health endpoint invoked frequently which results in the ZookeeperDiscoveryHealthIndicator being invoked. It turns out this zookeeper health check is sort of expensive(it takes 300+ ms in prod), and we want to disable it while keep the other health checks.

I went through http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html, it seems there is no way to disable default health check like others.

**Comment by spencergibb** [comment]
@zdlgrj the property wouldn't be in the spring-boot docs.

There currently isn't an option.

As a workaround you could extend `ZookeeperDiscoveryHealthIndicator` and override `health()` with an empty implementation and create it as a bean.
