### ISSUE TITLE
can use listOfServers if service not supported to register on ZooKeeper

### ISSUE THREAD

**Issue by bigc2000** [spring-cloud/spring-cloud-zookeeper#104]
When  integrated with ZUUL as edge server,  if some service not or cannot registered on ZooKeeper quorum, it will not benefit from static ZUUL properties:`{serviceId}.ribbon.listOfServers=host:port.`

**Comment by spencergibb** [comment]
Yes, From the [documentation](http://cloud.spring.io/spring-cloud-static/Camden.SR3/#_customizing_the_ribbon_client_using_properties)

```
<serviceId>:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers=host:port
```

**Comment by bigc2000** [comment]
Thanks!  And it works well, but if I want  listOfServers configuration to be a backup not instead of ZK configuration. So when connect to ZK failed, it can also choose static routes.

**Comment by spencergibb** [comment]
That is not supported

**Comment by bigc2000** [comment]
Sorry, 
as your advice,`NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList`
When I tried again with my zk quorum , it seems not work.
Could you do me a favor, give me more details?

I had made a big mistake, at the first time, it seemed work because I did not use zk at all( I modified my configs before for this problem)

I tried my best but failed, and at last I modified  the zookeeper discovery model sources
the class `org.springframework.cloud.zookeeper.discovery.ZookeeperServerList`.
But it is a bad solution.

**Comment by spencergibb** [comment]
@bigc2000 Writing your own server list implementation that uses zookeeper and falls back to configuration is the only way to achieve what you are looking for.
