### ISSUE TITLE
NPE in zookeeperdiscoveryclient when instance-port not specified

### ISSUE THREAD

**Issue by jorgheymans** [spring-cloud/spring-cloud-zookeeper#107]
I am seeing a strange NPE in ZKDC when the client is accessed first time to load the list of service instances: 

```
java.lang.NullPointerException: null
	at org.springframework.cloud.zookeeper.discovery.ZookeeperDiscoveryClient.getInstances(ZookeeperDiscoveryClient.java:89)
```

It seems that under certain conditions, ZookeeperServiceDiscovery.build() is never called - and the bulk of init work is being done there.  After adding the property `spring.cloud.zookeeper.discovery.instance-port` the npe went away. The instance-port property is optional though, it should default to the listen port. 

Note that the only other zookeeper related property i am using is `spring.cloud.zookeeper.connect-string`

**Comment by spencergibb** [comment]
Can you recreate the "certain conditions" required so we can write a test? Also what version are you using?

**Comment by jorgheymans** [comment]
Version 1.0.3, the only config property I had defined was the zookeeper
connection string.

Op vr 27 jan. 2017 16:49 schreef Spencer Gibb <notifications@github.com>:

**Comment by spencergibb** [comment]
I believe 1b44ab895f99fbd37a06f867651af1fb95b33032 fixed this. Can you try with 1.0.4.BUILD-SNAPSHOT?

**Comment by jorgheymans** [comment]
I tried the snapshot, no difference.

To clarify, when i deploy with these properties it works:
`
spring.cloud.zookeeper.connect-string=...
spring.cloud.zookeeper.discovery.instance-port=...
`
when i leave out the instance-port it doesn't.  Happy to provide any debug logs if needed.

**Comment by spencergibb** [comment]
The new code I linked to can't have the same NPE. There is a null check now https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-discovery/src/main/java/org/springframework/cloud/zookeeper/discovery/ZookeeperDiscoveryClient.java#L97-L100

So either you have a different error, or aren't using the new code.

**Comment by jorgheymans** [comment]
I admit I did not check if the npe was exactly the same, will do so next
week when I'm back in the office.

Op ma 30 jan. 2017 18:32 schreef Spencer Gibb <notifications@github.com>:

**Comment by jorgheymans** [comment]
looking at this a bit more closely now, I can no longer reproduce the issue with 1.0.4 SNAPSHOT. It seems that before i was still using 1.0.3 even though i thought i had did the necessary pom changes.

**Comment by jorgheymans** [comment]
oops seems i spoke too soon, it works under Tomcat but not when deployed under Weblogic. Can you confirm i am using the correct dependencies ? In dep mgmt i have this:
```
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-zookeeper-dependencies</artifactId>
        <version>1.0.4.BUILD-SNAPSHOT</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

and in the dependencies this:
```
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-zookeeper-discovery</artifactId>
      <version>1.0.4.BUILD-SNAPSHOT</version>
    </dependency>
```

exception
```
java.lang.NullPointerException: null
        at org.springframework.cloud.zookeeper.discovery.ZookeeperDiscoveryClient.getInstances(ZookeeperDiscoveryClient.java:89)
```

**Comment by jorgheymans** [comment]
turned out again to be a dependencies problem, spring-boot starter deps are really a pain. So i had to put all these 3 deps in my pom to actually get the right snapshot dependencies:

```
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-zookeeper</artifactId>
      <version>1.0.4.BUILD-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-zookeeper-discovery</artifactId>
      <version>1.0.4.BUILD-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-zookeeper-core</artifactId>
      <version>1.0.4.BUILD-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-zookeeper-discovery</artifactId>
      <version>1.0.4.BUILD-SNAPSHOT</version>
    </dependency>
```

Do you plan to release 1.0.4 anytime soon ?

**Comment by lurongjiang** [comment]
Has the issue been fixed?I am trouble in the same NPE with spring-cloud-starter-zookeeper-discovery with version 2.2.5.RELEASE.It seem assign Null to int.
From [spring-cloud document](https://docs.spring.io/spring-cloud-zookeeper/docs/2.2.5.RELEASE/reference/html/#spring-cloud-zookeeper-install),I found :
> See the [installation documentation](https://zookeeper.apache.org/doc/current/zookeeperStarted.html) for instructions on how to install Zookeeper.
>
> Spring Cloud Zookeeper uses Apache Curator behind the scenes. While Zookeeper 3.5.x is still considered "beta" by the Zookeeper development team, the reality is that it is used in production by many users. However, Zookeeper 3.4.x is also used in production. Prior to Apache Curator 4.0, both versions of Zookeeper were supported via two versions of Apache Curator. Starting with Curator 4.0 both versions of Zookeeper are supported via the same Curator libraries.
>
> In case you are integrating with version 3.4 you need to change the Zookeeper dependency that comes shipped with `curator`, and thus `spring-cloud-zookeeper`. To do so simply exclude that dependency and add the 3.4.x version like shown below.

But I try to upgrade zookeeper from 3.5.8 to 3.7.0,It doesn't work.

**Comment by spencergibb** [comment]
@lurongjiang yes, 4 years ago in 1.x. 2.x is no longer supported. 

If you can recreate the error in 3.0.x, please open a new issue and take the time to provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) (something that we can unzip attached to that issue or git clone, build, and deploy) that reproduces the problem.

**Comment by lurongjiang** [comment]
@spencergibb 
Thanks.I found out why it didn't work in my project.I debugger and get the byte for path from curator client,the data:

```json
{
  "payload": {
    "@class": "org.springframework.cloud.zookeeper.discovery.ZookeeperInstance",
    "metadata": {
      "groupId": "WGQ",
      "role": "TestApp-LRJ",
      "instance_status": "UP"
    },
    "name": "TestApp",
    "id": "TestApp-1"
  },
  "registrationTimeUTC": 1635852567130,
  "serviceType": "DYNAMIC",
  "sslPort": null,
  "uriSpec": {
    "parts": [
      {
        "variable": true,
        "value": "scheme"
      },
      {
        "variable": false,
        "value": "://"
      },
      {
        "variable": true,
        "value": "address"
      },
      {
        "variable": false,
        "value": ":"
      },
      {
        "variable": true,
        "value": "port"
      }
    ]
  },
  "address": "localhost",
  "name": "TestApp",
  "id": "TestApp-1",
  "port": 8086
}
```

then I tried to deserialize the data to ZookeeperInstance,the code

```java
public class TestDeserialize {
    public static void main(String[] args) throws Exception {
        Path path = Paths.get(args[0]);
        byte[] bytes = Files.readAllBytes(path);
        JsonInstanceSerializer<ZookeeperInstance> serializer = new JsonInstanceSerializer<>(ZookeeperInstance.class);
        ServiceInstance<ZookeeperInstance> instanceServiceInstance = serializer.deserialize(bytes);
        System.out.println(instanceServiceInstance.getName());
    }
}
```

then I got the json string

```json
{"name":"","id":"","address":null,"port":null,"sslPort":null,"payload":null,"registrationTimeUTC":0,"serviceType":"DYNAMIC","uriSpec":null,"enabled":true}
```

then I found the ObejctMapper was from org.codehaus.jackson:jackson-mapper-asl:1.8.8.

I realized that it might be a dependency omit problem.I exclude the jackson from hadoop, then it work

```xml
<dependency>
    <groupId>org.apache.hadoop</groupId>
    <artifactId>hadoop-yarn-client</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

It just was a bug in my code.Thank for your reply.
