### ISSUE TITLE
Update to curator framework 4.0.1

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-zookeeper#109]
- [3.2.1 release notes](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12314425&version=12336949)
- [3.2.0 release notes](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12314425&version=12335829)
- [3.1.0 release notes](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12314425&version=12333884)
- [3.0.0 release notes](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12314425&version=12326664)

**Comment by spencergibb** [comment]
For edgware or finchley

**Comment by lzimd** [comment]
Is this time to upgrade?  Finchley.M9 Has Been Released

**Comment by spencergibb** [comment]
@lzimd no work has been done on this yet.

**Comment by spencergibb** [comment]
https://cwiki.apache.org/confluence/display/CURATOR/Releases
