### ISSUE TITLE
Mark zookeeper instances OUT_OF_SERVICE

### ISSUE THREAD

**Issue by grinfeld** [spring-cloud/spring-cloud-zookeeper#112]
Hi,
I need to use some additional info and to store it in payload. I found the meta-data Map exposed for this purpose, but in my case I need to change it during app life-cycle and update zookeeper (and other services should see these changes) . Maybe, somebody could point how to do this?
```
{
  "id": "someid",
  "address": "address",
  "port": ​21737,
  "sslPort": null,
  "payload":  {
  "name": "app:0",
  "metadata": {
     "number": 1 // at the some time, it changes to 2 and so on
  }
},
"registrationTimeUTC": ​1456326281161,
```

**Comment by spencergibb** [comment]
Can you say why? Metadata has generally been read only. It's not a database

**Comment by grinfeld** [comment]
yes, we have list of services which are connected to different external systems (different protocols) and if one of external systems is down (and it could go up and down eventually), I don't want to mark the whole service is down, but only some inner component. If service is back, it updates info, other services should make their decision according to this info.

Something like:
return discoveryClient.getServices("app").stream().filter(s -> s != null && s.getPayload() != null && match(s.getPayload().getSomeData())).collect(Collectors.toList())

**Comment by spencergibb** [comment]
That's why I wanted to know why.

The other service discovery systems (eureka & consul) have facilities to take instances out of service without removing them.

I need that same functionality to impelement https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-discovery/src/main/java/org/springframework/cloud/zookeeper/serviceregistry/ZookeeperServiceRegistry.java#L117-L126

Metadata might be a way to do that. It would need to be integrated into ribbon and the discovery client impl as well to filter out the "out of service" instances.

@marcingrzejszczak how did you use to deal with this?

**Comment by grinfeld** [comment]
I am a new in Spring "world" (so sorry if I say something stupid), but seems it sounds problematically to put it inside ServiceRegistery, since Zookeeper actually couldn't have "status"  different from "UP" and "Down" (file is reachable or not). Every app should/could interpreter the metadata different. Maybe ribbon (and others) should have some mechanism to define custom behavior according to (for example) some value in metadata. Of course we should have the option to change/update this value.

**Comment by spencergibb** [comment]
Sure, but once you have the mechanism to change one metadata field, you can change it for any field. I need the capability this release if it is related to UP and OUT_OF_SERVICE, otherwise, it would come later.

**Comment by grinfeld** [comment]
For me, it sounds good enough. Thanks.

**Comment by grinfeld** [comment]
Again, sorry if question is stupid - but if setStatus is not exposed in DiscoveryClient - how application could update status?

**Comment by spencergibb** [comment]
There's a new interface, `ServiceRegistry`

**Comment by spencergibb** [comment]
Ping @marcingrzejszczak re: https://github.com/spring-cloud/spring-cloud-zookeeper/issues/112#issuecomment-277084442

**Comment by marcingrzejszczak** [comment]
Sorry @spencergibb for the delay - I must have missed this issue :|

So initially we had no payload, then we wanted to introduce payload but that was a breaking change and we had a calamity after the change was introduced so we rolled back to not having any payload ;) 

IMO the metadata should be treated as a map that can be updated. With the Zookeeper CLI you can update keys thus we should allow the same with the API (but that's only my personal opinion).
