### ISSUE TITLE
Running Actuator endpoints on another port with Zookeeper discovery

### ISSUE THREAD

**Issue by damnhandy** [spring-cloud/spring-cloud-zookeeper#113]
Spring Boot will allow you to expose the Actuator end points on port different from the same HTTP port your application is running on by adding the following to your `application.yaml` file:

    management:
        port: 9018

Spring Cloud Zookeeper will fail if the health check URIs run on another port. I'm wondering if there is an undocumented property (found a few already) or if this is feature worth adding?

**Comment by spencergibb** [comment]
Can you explain, "Spring Cloud Zookeeper will fail if the health check URIs run on another portion"?

**Comment by damnhandy** [comment]
Right! I guess I missed that part. I'm referring to the health check URI. Spring Cloud Zookeeper will attempt to call the health check end point first and assume that the health check URI is located at `/health` and that it's running on the services primary HTTP/HTTPS port. So assuming the following values on a service:

    server:
      port: 9017
    management:
      port: 9018

When using issuing the health check, the Spring Cloud Zookeeper always attempts to access the `server.port` value and fails. It seems I can change the health check path by setting `spring.cloud.zookeeper.dependency.ribbon.loadbalancer.defaulthealthendpoint` but it doesn't seem to handle another port.

**Comment by spencergibb** [comment]
Looking at the code, have you tried `spring.cloud.zookeeper.dependency.ribbon.loadbalancer.defaulthealthendpoint=:9018/health`?

**Comment by damnhandy** [comment]
Problem is that I have multiple services behind our API Gateway with each management URI exposed on a different port. I'll give this a whirl and see how it goes.

**Comment by spencergibb** [comment]
Why would that be a problem? `defaulthealthendpoint=:${management.port}/health`

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
