### ISSUE TITLE
ConfigurationProperties class should use the @Validated annotation

### ISSUE THREAD

**Issue by JulianEberius** [spring-cloud/spring-cloud-zookeeper#117]
Since Spring 1.5, ConfigurationProperties that use validation annotations should add the `@Validated` annotation, see [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#configurationproperties-validation).

I'm currently using Spring Boot 1.5.2 with Spring Cloud Camden.RELEASE and ZooKeeper integration, which should be compatible. However, a lot of warnings are logged on startup (the following is only an excerpt):

```
2017-03-09 10:10:07.349  WARN 19788 --- [  restartedMain] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.zookeeper.ZookeeperProperties contains validation constraints but had not been annotated with @Validated.
2017-03-09 10:10:07.987  WARN 19788 --- [  restartedMain] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.zookeeper.config.ZookeeperConfigProperties contains validation constraints but had not been annotated with @Validated.
```

Currently, this seems to be an cosmetic issue only, but according to Spring Boot release notes, this will become mandatory in the future.

**Comment by risbarov** [comment]
Hello everyone!

The warning still present:

`2017-05-03 19:40:51.587  WARN 6734 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.zookeeper.config.ZookeeperConfigProperties contains validation constraints but had not been annotated with @Validated.`

Spring Boot: 1.5.2.RELEASE
Spring Cloud: Dalston.RELEASE

See [ZookeeperTest.zip](https://github.com/spring-cloud/spring-cloud-zookeeper/files/974138/ZookeeperTest.zip)

**Comment by spencergibb** [comment]
Hmm https://github.com/spring-cloud/spring-cloud-zookeeper/blob/v1.1.0.RELEASE/spring-cloud-zookeeper-core/src/main/java/org/springframework/cloud/zookeeper/ZookeeperProperties.java#L31

**Comment by spencergibb** [comment]
But doesn't look like it is in the jar :-(

**Comment by spencergibb** [comment]
Different class

**Comment by emersonf** [comment]
Here's a reference to the Spring Boot release notes mentioned by @JulianEberius.

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#configurationproperties-validation
