### ISSUE TITLE
Configuration Multiple Connect String

### ISSUE THREAD

**Issue by NaviRamyle** [spring-cloud/spring-cloud-zookeeper#118]
It is possible to have multiple values in `spring.cloud.zookeeper.connect-string`?

Something like this
`spring.cloud.zookeeper.connect-string=192.168.0.901:2181,192.168.0.902:2181,localhost:2181`

**Comment by marcingrzejszczak** [comment]
Yes it is. We're using https://curator.apache.org/apidocs/org/apache/curator/framework/CuratorFrameworkFactory.Builder.html#connectString-java.lang.String- under the hood to set the list of servers. So just pass it as you're suggesting.
