### ISSUE TITLE
spring.cloud.zookeeper.config.enabled=false is not enough to disable Zookeeper Config

### ISSUE THREAD

**Issue by Cs4r** [spring-cloud/spring-cloud-zookeeper#124]
It seems that  `org.springframework.cloud.zookeeper.config.ZookeeperPropertySourceLocator` still loads configuration properties from Zookeeper in spite of having set the property spring.cloud.zookeeper.config.enabled to false in bootstrap.yml (As http://cloud.spring.io/spring-cloud-zookeeper/spring-cloud-zookeeper.html#_customizing suggests).

spring.cloud.zookeeper.enabled set to false disables the loading of properties from zookeeper however it also disables other features that use zookeeper (e.g: service discovery)

IMHO, ZookeeperPropertySourceLocator would had to check the value of properties.isEnabled() before trying to create PropertySources from the list of contexts. 

Spring modules used and their versions:
- 'org.springframework.boot:spring-boot-starter-web'  ->  '1.4.3.RELEASE'
- 'org.springframework.cloud:spring-cloud-zookeeper-dependencies' and 'org.springframework.cloud:spring-cloud-starter-zookeeper-config' -> 1.1.0.RELEASE

**Comment by spencergibb** [comment]
Yes, that check is missing.

**Comment by spencergibb** [comment]
PRs welcome

**Comment by Cs4r** [comment]
Sure. I will create a PR either today or tomorrow

**Comment by Cs4r** [comment]
I think my PR fixes the issue describe in this ticket.

Let me know if I need to do something else before merging :smile: 

Regards
