### ISSUE TITLE
 What’s the purpose of uriSpec in ZookeeperDiscoveryProperties?

### ISSUE THREAD

**Issue by wuxianInfi** [spring-cloud/spring-cloud-zookeeper#127]
/**
	 * The URI specification to resolve during service registration in Zookeeper
	 */
	private String uriSpec = DEFAULT_URI_SPEC;

What’s the purpose of uriSpec in ZookeeperDiscoveryProperties?

**Comment by spencergibb** [comment]
It's a required field for the curator [service discovery recipe](http://curator.apache.org/curator-x-discovery/index.html).

See http://curator.apache.org/apidocs/org/apache/curator/x/discovery/ServiceInstance.html
