### ISSUE TITLE
Documenting use of SSL and ACLs

### ISSUE THREAD

**Issue by dfeblowitz** [spring-cloud/spring-cloud-zookeeper#128]
Hello,

I recently integrated spring-cloud-zookeeper into a project that I'm working on that required the use of SSL and ACLs. I couldn't find documentation on this so I'd like to explain how I got this set up, in case I could help contribute to the project docs or you have a recommendation of how it could be done better.

To enable SSL, I set the following system properties:
 ```-Dzookeeper.client.secure=true
  -Dzookeeper.ssl.context=TLSv1.2
  -Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty
  -Dzookeeper.ssl.keyStore.location=<keystore location>
  -Dzookeeper.ssl.trustStore.location=<truststore location>
  -Dzookeeper.ssl.keyStore.location=<keystore password>
  -Dzookeeper.ssl.trustStore.location=<truststore password>
```
I also had to add `org.apache.zookeeper:zookeeper` as a dependency, as the ClientCnxnSocketNetty class was not available.

For ACLs, I defined a \@BootstrapConfiguration class that depends on the existing CuratorFramework bean and called its addAuthInfo method with my authentication info.

Is there a better way to do either of these things? Could I be of any assistance creating documentation for this?

**Comment by spencergibb** [comment]
We always welcome pull requests.

**Comment by WhiteStart** [comment]
> 
could you place more codes and details,I got the same question
