### ISSUE TITLE
Add support for curator ServiceInstance.sslPort

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-zookeeper#132]

**Comment by ExtremeYu** [comment]
hello,is this issue fixed?

**Comment by spencergibb** [comment]
@ExtremeYu yes, but not released.

**Comment by mbhuie** [comment]
It works when below is specified

> spring.cloud.zookeeper.discovery.instance-ssl-port 

This leads to constant port number. If my server.port: 0 so that my application can randomly choose a port

why cann't this be derived from 

> server.port: 0

and

> server.ssl.enabled : true

**Comment by spencergibb** [comment]
@mbhuie please don't comment on a closed issue, open a new one if you think there's an opportunity for enhancement.

**Comment by mbhuie** [comment]
#150 created
