### ISSUE TITLE
Examples for Ribbon and Hystrix ?

### ISSUE THREAD

**Issue by dANGsx** [spring-cloud/spring-cloud-zookeeper#135]
Like title description, I can't find examples using Ribbon and Hystrix with zookeeper. Where should I looking for an example?

**Comment by spencergibb** [comment]
The documentation here http://cloud.spring.io/spring-cloud-static/Dalston.SR1/ for Ribbon and Hystrix works regardless of discovery provider.

**Comment by dANGsx** [comment]
Thanks
