### ISSUE TITLE
Does ContextRefresher.refresh impact the application's performance?

### ISSUE THREAD

**Issue by wuxianInfi** [spring-cloud/spring-cloud-zookeeper#136]
ContextRefresher.refresh will be invoked every time when any configuration attribute is updated in zookeeper. Does ContextRefresher.refresh impact the application's performance? or block the application running?

**Comment by spencergibb** [comment]
It depends. Do you have beans that are marked as `@RefreshScope`. It shouldn't block the application.

**Comment by wuxianInfi** [comment]
So it depends on whether we have beans that are marked as @RefreshScope or not? If we have, what the approximate extent of impact？

**Comment by spencergibb** [comment]
When refresh is called, beans that are marked `@RefreshScope` are recreated. So the creation of those beans is a variable that I can't determine.
