### ISSUE TITLE
spring.cloud.zookeeper.connectString is not work

### ISSUE THREAD

**Issue by s332401890** [spring-cloud/spring-cloud-zookeeper#137]
when i config spring.cloud.zookeeper.connectString in application.properties,it also connect to localhost.

i read the code in ZookeeperAutoConfiguration if add "@EnableConfigurationProperties(ZookeeperProperties.class) in  ZookeeperAutoConfiguration"
i think it will work.

**Comment by s332401890** [comment]
1.0.0

**Comment by spencergibb** [comment]
Are you using zookeeper configuration? Please see the caution here http://cloud.spring.io/spring-cloud-static/Dalston.SR1/#_registering_with_zookeeper

It likely needs to go in bootstrap.properties.

**Comment by s332401890** [comment]
thinks~
