### ISSUE TITLE
release with fix for secure services planned?

### ISSUE THREAD

**Issue by jimguistwite** [spring-cloud/spring-cloud-zookeeper#142]
I noticed the fix for zookeeper-based service registration and discovery for secure (https) services in the source but I don't believe it made it into a release.   Is there a release 1.1.2 planned that would include the fix to support secure services?

**Comment by spencergibb** [comment]
Which particular fix did you see? https://github.com/spring-cloud/spring-cloud-zookeeper/milestone/13?closed=1 will likely be in the next week or so, GA, either end of August or more likely September

**Comment by spencergibb** [comment]
Monday Aug 21
