### ISSUE TITLE
Missing metadata for zookeeper discovery

### ISSUE THREAD

**Issue by ileler** [spring-cloud/spring-cloud-zookeeper#151]
Why does not provide a unified list of configuration items?
I found this configuration item ·spring.cloud.zookeeper.discovery.instanceIpAddress· to find a long time to find.

**Comment by spencergibb** [comment]
You mean this? http://cloud.spring.io/spring-cloud-static/Dalston.SR4/single/spring-cloud.html#_appendix_compendium_of_configuration_properties

**Comment by spencergibb** [comment]
It should be in the list automatically

**Comment by ileler** [comment]
Thank you ^*^ 
I want to know how to automatically add to this list? Is there any norm? I am sorry, I understand the spring-cloud is not very thorough.n_n

**Comment by spencergibb** [comment]
It's a bug in our automated process

**Comment by ileler** [comment]
yes,i know...and can you give me your automated process project github repo address?

**Comment by ryanjbaxter** [comment]
We have an issue open that covers updating that appendix https://github.com/spring-cloud/spring-cloud-release/issues/97
