### ISSUE TITLE
Don't fail DiscoveryClient when curator throws NoNodeException.

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-zookeeper#164]
https://github.com/spring-cloud/spring-cloud-netflix/issues/2269#issuecomment-374262975

**Comment by spencergibb** [comment]
Closed via dab8f973a577d9293e8c6620f0046aa90c1df9fa

**Comment by iNikem** [comment]
Is there any estimate, when new 2.0 milestone with this fix will be released?

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-release/milestones?direction=asc&sort=due_date

**Comment by Jo212** [comment]
it appears that when the topic does not exists this exception is thrown.
