### ISSUE TITLE
The register sevice bug

### ISSUE THREAD

**Issue by liuzhebaba** [spring-cloud/spring-cloud-zookeeper#183]
if you write a services on your zk like this /services/test/10.1.1.1  ，but no jsonData in this node，all services can't visit。I think this problem is very serious。if I want join up a service not use java manual。the hole services can't visit

**Comment by spencergibb** [comment]
We use the curator discovery mechanism. However you are doing external registration needs to be compatible.

**Comment by liuzhebaba** [comment]
> We use the curator discovery mechanism. However you are doing external registration needs to be compatible.

fine
