### ISSUE TITLE
Double refresh of beans

### ISSUE THREAD

**Issue by EraCat** [spring-cloud/spring-cloud-zookeeper#188]
Hello! 
I have Spring Boot Application with spring cloud starter auto configuration for zookeeper.
I met some problems with refreshing context when I do some changes in zookeper nodes.
This is my ```pom.xml```:
```
    <properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>
        <camel.version>2.23.1</camel.version>
        <spring-boot.version>2.1.2.RELEASE</spring-boot.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-zookeeper-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zookeeper-config</artifactId>
        </dependency>
```
And I have two questions:
1. When I configure bootstrap.yml, for example:
```spring:
  cloud:
    zookeeper:
      connect-string: localhost:2181
      config:
        enable: true
        root: config
        defaultContext: apps
        profileSeparator: '::'
  application:
    name: my_application 
```
then created two ```propertySourceContext```: "config/apps" and "config/my_application" in ```ZookeeperPropertySourceLocator```
It was not obvious to me, that ```application.name```is used to build path to zookeper node. 
Why do i need ```defaultContext``` and ```application.name``` both to build paths? I really want understand that) 
When i use  ```defaultContext``` and ```application.name``` with same name,
then it leads to creation of two two ```propertySourceContext``` and  all ```RefreshScope``` beans refreshing two times, is it normal?)

2. I use ```@EventListener(RefreshScopeRefreshedEvent.class)```(for refreshing method) for catching refresh my ZooKeeper, but any change in my ZooKeeper call this method:( 
Can i subscribe on some Node in zookeeper and refresh only certain beans?
I saw the method named ```public boolean refresh(String name) ``` in  ```RefreshScope.class```,  how can I invoke it?

Thanks!
P.S. Sorry for my best english!

**Comment by spencergibb** [comment]
the `defaultContext` is a place to put properties that are common to apps. It shouldn't be the same as `spring.application.name`.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by EraCat** [comment]
I realized that i should not specify the same values. 
What about the second question? 
Can I subscribe to a specific node, or will any change in zookeeper always refresh context?

**Comment by EraCat** [comment]
Thank you very much for your attention!
I figured this out a bit and just want to clarify. When changing the node in the zookeeper `RefreshScopeRefreshedEvent` event throws or is there a more specific event?

**Comment by EraCat** [comment]
I think I found the answer to my question)
I can catch the refresh event and check on instance of `TreeCacheEvent`
then determine the updated node and do what you want)
Example 
```
 @EventListener(RefreshEvent.class)
    public void onRefresh(RefreshEvent event)  {
...
}
```
If there is a better way please correct me!
Thank you very much for your attention!
