### ISSUE TITLE
Doesn't immediately out of service in Zookeeper.

### ISSUE THREAD

**Issue by kapentaz** [spring-cloud/spring-cloud-zookeeper#226]
I am using Spring Cloud Zookeeper for Service Discovery.
When I deploy a microservice before call endpoint '/service-registry'.

e.g.
```
curl --data '{"status":"OUT_OF_SERVICE"}' --header "Content-Type: application/json" -X POST http://localhost:8040/actuator/service-registry
```

and then i can see this by ZK-Web
```
{"name":"...","id":"06c0af4c-03c4-4cc1-a702-050303b41b8b","address":"....","port":8040,"sslPort":null,"payload":{"@class":"org.springframework.cloud.zookeeper.discovery.ZookeeperInstance","id":"...","name":"....","metadata":{"instance_status":"OUT_OF_SERVICE"}},"registrationTimeUTC":1553592092875,"serviceType":"DYNAMIC","uriSpec":{"parts":[{"value":"scheme","variable":true},{"value":"://","variable":false},{"value":"address","variable":true},{"value":":","variable":false},{"value":"port","variable":true}]}}
```

I expected that any microservice don't call that service because The instance_status is "OUT_OF_SERVICE"

but it's possible to call the microservice even if its status is "OUT_OF_SERVICE".

In fact, the microservice is out of service in zookeeper after shutdown.

Did I do something wrong? or Do I need more config?

**Comment by spencergibb** [comment]
This has to propagate thru ribbon caches.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
