### ISSUE TITLE
issues about zookeeper and spring cloud config

### ISSUE THREAD

**Issue by hongdaliu** [spring-cloud/spring-cloud-zookeeper#228]
Thanks for raising a Spring Cloud issue. What sort of issue are you raising?

Question

a bug with spring zookeeper and spring cloud config

Bug report

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-04-17 10:15:57.657 ERROR 6508 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'zookeeperDiscoveryProperties', defined in class path resource [org/springframework/cloud/zookeeper/discovery/configclient/ZookeeperDiscoveryClientConfigServiceBootstrapConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/cloud/zookeeper/discovery/ZookeeperDiscoveryAutoConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

2019-04-17 10:15:57.660 ERROR 6508 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

Enhancement

spring:
  application:
    name: config-server
  cloud:
    config:
      name: bus
      enabled: false
      discovery:
        enabled: true
        service-id: ${spring.application.name}
      server:
        git:
          search-paths:
          - microservice
          - apps
          uri: 
          username: 
          password: 
    zookeeper:
      enabled: true
      connect-string: 
      discovery:
        enabled: true
        register: true
        instance-id: ${spring.application.name}

**Comment by spencergibb** [comment]
Please supply the versions of spring boot and cloud that you are using.

**Comment by hongdaliu** [comment]
> Please supply the versions of spring boot and cloud that you are using.

my zookeeper version is 3.4.14

pom.xml
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.0.M1</version>
		<relativePath/> 
	</parent>

<dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-starter-zookeeper-discovery</artifactId>
		    <exclusions>
				<exclusion>
				  <groupId>org.apache.zookeeper</groupId>
				  <artifactId>zookeeper</artifactId>
				</exclusion>
		    </exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.zookeeper</groupId>
			<artifactId>zookeeper</artifactId>
			<version>3.4.14</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by hongdaliu** [comment]
> Please supply the versions of spring boot and cloud that you are using.
`<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.0.M1</version>
		<relativePath/> 
	</parent>`
`<dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-starter-zookeeper-discovery</artifactId>
		    <exclusions>
				<exclusion>
				  <groupId>org.apache.zookeeper</groupId>
				  <artifactId>zookeeper</artifactId>
				</exclusion>
		    </exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.zookeeper</groupId>
			<artifactId>zookeeper</artifactId>
			<version>3.4.14</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>
			</exclusions>
		</dependency>`

**Comment by spencergibb** [comment]
Unless you are using snapshots of spring cloud Hoxton (which I don't know since you didn't supply them), it is not compatible with boot 2.2.x

**Comment by hongdaliu** [comment]
> Unless you are using snapshots of spring cloud Hoxton (which I don't know since you didn't supply them), it is not compatible with boot 2.2.x

when i use spring cloud zookeeper config , it dont have config properties promote in bootstrap.yml

spring cloud zookeeper config center 
`
      config:
        enabled: true
        root: configuration
        defaultContext: apps
        profileSeparator: '::'`
