### ISSUE TITLE
Enhance the CuratorFramework such that it integrates with Curator's TraceDriver

### ISSUE THREAD

**Issue by berngp** [spring-cloud/spring-cloud-zookeeper#241]
**Context**

The existing `ZookeeperAutoConfiguration` offers no mechanism to provide a `TracerDriver` that can be added to the `CuratorsFramework`.  It is arguable that developers could add their own `CuratorFramework` bean since the `ZookeeperAutoConfiguration` has it as a `ConditionalOnMissingBean`. That said, they would end up replicate most of the method's behavior just to add a couple of lines of code. 

The TraceDriver can be added as follows...

```
curator.getZookeeperClient().setTracerDriver(tracerDriver);
```

**Suggested Solution**
Update the `curatorFramework` method to optionally accept an instance of `TracerDriver`. e.g.:

```
        @Bean(destroyMethod = "close")
	@ConditionalOnMissingBean
	public CuratorFramework curatorFramework(RetryPolicy retryPolicy, ZookeeperProperties properties,
			@Autowired(required = false) TracerDriver tracerDriver,
			@Autowired(required = false) EnsembleProvider ensembleProvider) throws Exception {
		CuratorFrameworkFactory.Builder builder = CuratorFrameworkFactory.builder();
		if (ensembleProvider != null) {
			builder.ensembleProvider(ensembleProvider);
		}
		else {
			builder.connectString(properties.getConnectString());
		}
		CuratorFramework curator = builder.retryPolicy(retryPolicy).build();
		if (tracerDriver != null) {
			curator.getZookeeperClient().setTracerDriver(tracerDriver);
		}

		curator.start();
		log.trace("blocking until connected to zookeeper for " + properties.getBlockUntilConnectedWait()
				+ properties.getBlockUntilConnectedUnit());
		curator.blockUntilConnected(properties.getBlockUntilConnectedWait(), properties.getBlockUntilConnectedUnit());
		log.trace("connected to zookeeper");
		return curator;
	}
```

**Describe alternatives you've considered**

As mentioned above I have implemented my own `CuratorFramework` bean since the `ZookeeperAutoConfiguration` has it as a `ConditionalOnMissingBean`. That said, I ended up copying most of the current behavior just to add a couple of lines of code. 

References:
1. https://github.com/apache/curator/blob/master/curator-client/src/main/java/org/apache/curator/drivers/EventTrace.java
2. https://github.com/apache/curator/blob/master/curator-client/src/main/java/org/apache/curator/ConnectionState.java
3. https://github.com/apache/curator/blob/master/curator-client/src/main/java/org/apache/curator/RetryLoop.java

**Comment by spencergibb** [comment]
PRs welcome

**Comment by berngp** [comment]
Will do @spencergibb , thanks for the quick update.
