### ISSUE TITLE
Zookeeper config starter does not depend on spring-boot-starter

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-zookeeper#248]
This causes integration test failures in start.spring.io

**Comment by snicoll** [comment]
Thanks @spencergibb. I am confused about the `2020.0` milestone though as the snapshot version for `2020.0` was already valid.

**Comment by spencergibb** [comment]
regardless of the initializr validity spring-cloud-zookeeper-starter did not depend on spring-cloud-starter.
