### ISSUE TITLE
Document dependency functionality

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-zookeeper#25]
in `org.springframework.cloud.zookeeper.discovery.dependency`

**Comment by spencergibb** [comment]
@marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
So as not to forget:
> spring-cloud-zookeeper.adoc somewhere under the discovery section

**Comment by marcingrzejszczak** [comment]
@spencergibb  - do we close this one?

**Comment by spencergibb** [comment]
Closed via 82028fd8f532e510bec61a1a9fdca2651ae475fa
