### ISSUE TITLE
DynamicServerListLoadBalancer is super-slow in case of dependencies are used

### ISSUE THREAD

**Issue by michail-nikolaev** [spring-cloud/spring-cloud-zookeeper#268]
Affected version: 2.2.1.RELEASE
DynamicServerListLoadBalancer is super-slow in case of dependencies are used because of `updateListOfServers` call.

https://github.com/spring-cloud/spring-cloud-zookeeper/blob/a9ae6f734bcd791838e437a196f9899db911a6d5/spring-cloud-zookeeper-discovery/src/main/java/org/springframework/cloud/zookeeper/discovery/dependency/DependenciesBasedLoadBalancer.java#L80

Each call to underlying services causes the load balancer to call `updateListOfServers`. It causes a Zookeeper scan and, possibly, a set of pings to validate the availability of the servers.

**Comment by OlgaMaciaszek** [comment]
Closing since Ribbon load-balancing is no longer supported.
