### ISSUE TITLE
Zookeeper connect-string not being red

### ISSUE THREAD

**Issue by iron2414** [spring-cloud/spring-cloud-zookeeper#269]
**Describe the bug**
If i use the latest spring-cloud-zookeper, if i start my application it tries to connect to localhost:2181 instead of my "1.2.3.4:2181".
If i use the dependencies from the baeldung example, it connects to "1.2.3.4:2181" properly.

Working pom xml:
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zookeeper-discovery</artifactId>
            <version>2.2.4.RELEASE</version>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Hoxton.SR4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

not working pom.xml:
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zookeeper-all</artifactId>
            <version>2.2.4.RELEASE</version>
        </dependency>
```

application-default.properties:
```
spring.cloud.zookeeper.connect-string=1.2.3.4:2181
```

I debugged it back, it should be red, in org.springframework.cloud.zookeeper.ZookeeperProperties.setConnectString method. But it's not being called.

Any help would be appreciated

**Comment by spencergibb** [comment]
because you use the `-all` starter, that includes config, which mean that the connect string needs to be set in `bootstrap.properties`.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
