### ISSUE TITLE
Collections.reverse in ZookeeperPropertySourceLocator#locate re-reverses orderer already reversed in ZookeeperPropertySources#getAutomaticContexts

### ISSUE THREAD

**Issue by msievers** [spring-cloud/spring-cloud-zookeeper#270]
**Describe the bug**
With the latest `2020.0.0-M6` and `spring-cloud-starter-zookeeper-config` I noticed, that that property sources for the default (Zookeeper) node are ordered *before* their respective counterparts for the specific node (e.g. identified by application name).

I think the problem is, that the Zookeeper contexts are reversed two times
* https://github.com/spring-cloud/spring-cloud-zookeeper/blob/4cf27efdbeea47f942adb986da3b7b35dbfc6f47/spring-cloud-zookeeper-config/src/main/java/org/springframework/cloud/zookeeper/config/ZookeeperPropertySources.java#L52
* https://github.com/spring-cloud/spring-cloud-zookeeper/blob/4cf27efdbeea47f942adb986da3b7b35dbfc6f47/spring-cloud-zookeeper-config/src/main/java/org/springframework/cloud/zookeeper/config/ZookeeperPropertySourceLocator.java#L95-L99

which in fact restores the original order and (for me) brings the default/common Zookeeper nodes in front of the specific ones.

Feel free to ping me if I can be of any further help.

**Comment by ryanjbaxter** [comment]
Is it just a problem in the latest milestone?  I have you tried to reproduce it in earlier milestones?

**Comment by msievers** [comment]
The changes were introduced by this commit

https://github.com/spring-cloud/spring-cloud-zookeeper/commit/4cf27efdbeea47f942adb986da3b7b35dbfc6f47

which is marked with `M4`, so I guess this affects >= `M4`.

**Comment by msievers** [comment]
I think I can provide a (failing) unit test for this. I will create (and link) the merge request.

**Comment by msievers** [comment]
I created a merge request (see #271), which includes

* a unit tests which checks the correct order of the property sources in the CompositePropertySource
* a fix, by removing the redundant `reverse` call
