### ISSUE TITLE
No spring configuration metadata is generated for ZookeeperConfigProperties due to missing spring-boot-configuration-processor

### ISSUE THREAD

**Issue by msievers** [spring-cloud/spring-cloud-zookeeper#272]
There is no configuration metadata being generated for
* `org.springframework.cloud.zookeeper.config.ZookeeperConfigProperties`

because actually `spring-boot-configuration-processor` is missing in `spring-cloud-zookeeper-config/pom.xml`.

This probably also relates to #174.

It should be rather easy to fix, by adding `spring-boot-configuration-processor` to the pom. I will create PR for this.

**Comment by ryanjbaxter** [comment]
Fixed via 009ee54
