### ISSUE TITLE
Replace usage of deprecated StringUtils.isEmpty with !StringUtils.hasLength

### ISSUE THREAD

**Issue by msievers** [spring-cloud/spring-cloud-zookeeper#274]
As of Spring 5.3 `StringUtils.isEmpty` is deprecated. The official migration hint is to either use one of the following:
* `!StringUtils.hasLength`
* `!StringUtils.hasText`

To keep behaviour *exactly* the way it is, `!StringUtils.hasLength` can be used to replace the current usage of `StringUtils.isEmpty`.

**Comment by ryanjbaxter** [comment]
Closed via 991cfbf
