### ISSUE TITLE
ZookeeperConfigBootstrapConfiguration does not pick up spring.application.name defined in application.properties when using Bootstrap (regression)

### ISSUE THREAD

**Issue by msievers** [spring-cloud/spring-cloud-zookeeper#276]
I tried to migrate one of our applications using `spring-cloud-starter-zookeeper-config` from
* `2.2.4.RELEASE` to `3.0.0-SNAPSHOT`

Therefor I simply update the pom like this

```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-zookeeper-config</artifactId>
    <version>3.0.0-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bootstrap</artifactId>
    <version>3.0.0-SNAPSHOT</version>
</dependency>
```

This way it should still use the bootstrap context and everything should just work as before.

The application has properties like this

```properties
# bootstrap.properties
spring.cloud.zookeeper.connect-string=some-zookeeper:2181
spring.cloud.zookeeper.config.root=some/node
spring.cloud.zookeeper.config.defaultContext=common
```

```properties
# application.properties
spring.application.name=my-app
```

With `2.2.4.RELEASE`, `spring.application.name` is picked up from `application.properties` and used to build the Zookeeper path like this `some/node/my-app`.

When upgrading to `3.0.0-SNAPSHOT`, it gives to `some/node/application`. In fact, it does not consider `spring.application.name` from the `application.properties`.

I chased it down to `ZookeeperConfigBootstrapConfiguration`
* https://github.com/spring-cloud/spring-cloud-zookeeper/blob/d65b9a0310ecae6e7f2283520baf7d7f896308cb/spring-cloud-zookeeper-config/src/main/java/org/springframework/cloud/zookeeper/config/ZookeeperConfigBootstrapConfiguration.java#L52

In fact, you can either provide `spring.application.name` or the newly available `spring.cloud.zookeeper.config.name` directly in `bootstrap.properties`. which solves the problem.

But it's somehow a regression and existing apps, which just update their dependencies like I did will run into problems.

**Comment by msievers** [comment]
I would love to provide some PR for this if anybody could point me in the right direction.

**Comment by spencergibb** [comment]
Spring.application.name needs to be in bootstrap as well

**Comment by msievers** [comment]
Ok. Just wanted to point out that it definitely worked before, having `spring.application.name` in `application.properties` and because that worked before, there might be apps that will break after upgrade. This is definitely true for our apps, which all have `spring.application.name` in `application.properties`.

No big deal to migrate, if you know it. Just asking myself how many apps are set up this way and will try to upgrade just doing the same steps as I did (upgrading the version number and adding `spring-cloud-starter-bootstrap`)

**Comment by spencergibb** [comment]
I don't think it's possible that it worked before. Reading of application.properties happens after bootstrap

**Comment by msievers** [comment]
I have four apps app and running which prove that it does. How can I convince you :)

**Comment by msievers** [comment]
![spring-boot-cloud-zookeeper-application-name](https://user-images.githubusercontent.com/156371/101177866-93ca8380-3648-11eb-9a65-7eaa4f1a5a02.png)

In this screenshot, I just did with one of our apps, running `spring-boot-cloud-zookeeper-config:2.2.3` one can see, that the application name is not set in the `bootstrap.properties`, but it gets resolved to `my-app`, which is set in `application.properties`

**Comment by msievers** [comment]
Maybe there's no need to restore this behavior, but just add a sentence to the wiki (or any other migration guide), that this may have worked before (by accident) and that it will not work anymore with >= 3 and that these settings need to be put in `bootstrap.properties` (if bootstrap is used).

**Comment by spencergibb** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by msievers** [comment]
Sure. I'll create one :+1:

**Comment by msievers** [comment]
There you are:

https://github.com/msievers/spring-cloud-zookeeper-demo

The most challenging part actually was to seed some zookeeper values before the applications starts. I tried my best with docker-compose by letting a second container execute `zkCli.sh` against the first one running zookeeper.

Please run the docker compose file in the repositories root before starting the app for zookeeper to be available and seeded.

After seeding, there should values like
* `/config/root/my-app/someKey` = `someValue`
* `/config/root/default/someKey` = `someDefaultValue`
* `/config/root/default/otherKey` = `otherDefaultValue`

Configuration files look like this:

```properties
# bootstrap.properties
spring.cloud.zookeeper.connect-string=localhost:2181
spring.cloud.zookeeper.config.root=config/root
spring.cloud.zookeeper.config.defaultContext=default
```

```properties
# application.properties
spring.application.name=my-app
```

The application will log out the `someKey` and `otherKey` values on `ApplicationReady` like this

```java
@Slf4j
@SpringBootApplication
@RequiredArgsConstructor
public class Application implements ApplicationListener<ApplicationReadyEvent> {

	private final Environment environment;

	@Value("${spring.application.name}")
	private String applicationName;

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

	@Override
	public void onApplicationEvent(ApplicationReadyEvent applicationReadyEvent) {
	
		log.info("Application name is: {}", applicationName);
	
		final String someKey = "someKey";
		final String otherKey = "otherKey";
	
		log.info("Reading property: {} = {}", someKey, environment.getProperty(someKey));
		log.info("Reading property: {} = {}", otherKey, environment.getProperty(otherKey));
	}
}
```

which results in it logging

```
2020-12-04 20:27 INFO 242 --- [main] com.example.demo.Application: Application name is: my-app
2020-12-04 20:27 INFO 242 --- [main] com.example.demo.Application: Reading property: someKey = someValue
2020-12-04 20:27 INFO 242 --- [main] com.example.demo.Application: Reading property: otherKey = otherDefaultValue
```

**Comment by spencergibb** [comment]
I can't immediately explain why `PropertySourceBootstrapConfiguration` isn't running in bootstrap. But I can say it is unintended and not documented and not supported.

**Comment by msievers** [comment]
Yeah, as I said, I just wanted to point out, that it's currently possible to put `spring.application.name` in `application.properties` as well and that there is a (small) chance that people might run into this (like I did) when upgrading.

I will switch to use the new `spring.cloud.zookeeper.config.name` anyway, so for me, it was important to inform you about it.

Closing this one.

**Comment by spencergibb** [comment]
@dsyer this is an odd one to look at. Should get together to look at this.
