### ISSUE TITLE
After the service exits, the node on zk is not deleted in time, causing the rpc call to fail

### ISSUE THREAD

**Issue by ZMRWEGO** [spring-cloud/spring-cloud-zookeeper#279]
When I forcibly close the springboot program, the node information currently registered in zk is not deleted in time, but is automatically deleted at the next heartbeat time. Is there a solution currently?

**Comment by spencergibb** [comment]
I'm unsure what you are asking for. Zookeeper discovery is implemented using https://curator.apache.org/curator-x-discovery/index.html.

We have no control over what happens if the instance if forcibly exits and the connection to zookeeper is severed.

**Comment by ZMRWEGO** [comment]
Sorry, I mean if my service is offline, but the data of the service in zk is not deleted in time, the service may be called again, which may cause the call to fail

**Comment by spencergibb** [comment]
That's why there is retry and various other strategies when there are stale entries in discovery.

**Comment by ZMRWEGO** [comment]
ok，i'll try later.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
