### ISSUE TITLE
Is there possible for one app register itself as multiple services in the service registry?

### ISSUE THREAD

**Issue by Shoothzj** [spring-cloud/spring-cloud-zookeeper#305]
**Is your feature request related to a problem? Please describe.**
Is there possible for one app register itself as multiple services in the service registry? That will be transparent to the clients. The clients can still use the old service name to access the service.

**Describe the solution you'd like**
Is there any config can achieve this?

**Describe alternatives you've considered**
Is there possible to use an utility class to register services?

Thanks in advance. Any help wouble be greateful :)

**Comment by Shoothzj** [comment]
ping :)

**Comment by spencergibb** [comment]
Not automatically. You can use the `ServiceRegisitry` bean to do it manually.
