### ISSUE TITLE
Regression in `3.1.4`: customizations to the `CuratorFramework` instance are now silently ignored

### ISSUE THREAD

**Issue by pantherdd** [spring-cloud/spring-cloud-zookeeper#324]
**Describe the bug**

[`spring-cloud-zookeeper` release `3.1.4`](https://github.com/spring-cloud/spring-cloud-zookeeper/releases/tag/v3.1.4) introduced a **regression**. There were ways to customize the `CuratorFramework` instance that got used, e.g. by injecting a `CuratorFrameworkCustomizer` via a `registry.registerIfAbsent` call in a custom `BootstrapRegistryInitializer` that runs before `ZookeeperConfigServerBootstrapper`. **Such customizations worked flawlessly until version `3.1.3`, but in `3.1.4` they are now silently ignored.**

It doesn't look like there is an easy way to apply such customizations in the new version, other than copying [the old `registry.registerIfAbsent(ConfigServerInstanceProvider.Function.class, ...)` code from the PR](https://github.com/spring-cloud/spring-cloud-zookeeper/pull/317/files#diff-f29ec6dc3150e4b110618fecac383aea6584a736cea1da36bf5c27178518971eL106-L111) and overriding the new `ZookeeperFunction::create` implementation with it.

This change should be reverted; even if it makes sense to do this, it most definitely doesn't belong in a patch release.
Thanks.

**Comment by spencergibb** [comment]
It was part of https://github.com/spring-cloud/spring-cloud-commons/pull/1228 and https://github.com/spring-cloud/spring-cloud-config/issues/1922

@ryanjbaxter any ideas?

**Comment by ryanjbaxter** [comment]
Can you provide an sample illustrating the problem?  I see the problem you are describing, but I would like to have something concrete to work with that I can test a solution against.

**Comment by ryanjbaxter** [comment]
Yeah it doesnt have to do anything useful, just show that it was used in 3.1.3, but is no longer used in 3.1.4 (it could just print something to the console to show that)

**Comment by pantherdd** [comment]
@ryanjbaxter It wasn't too straightforward, but I managed to build a reproduction project: https://github.com/pantherdd/spring-cloud-zookeeper-issue-324

How to use:
1. Start a local ZooKeeper instance (I used latest `3.9.1` from [ZooKeeper Getting Started Guide](https://zookeeper.apache.org/doc/current/zookeeperStarted.html))
2. Build both subprojects (`gradle installDist`)
3. Start `configuration-service` (`java -jar configuration-service\build\install\configuration-service\configuration-service.jar`)
   * You should see a JSON containing `"message":"Hello from Spring Cloud Config"` at http://localhost:8065/configuration-client/default
4. Start `configuration-client` (`java -jar configuration-client\build\install\configuration-client\configuration-client.jar`)
   * You should see `Hello from Spring Cloud Config` at http://localhost:8066/message

Using `spring-cloud-dependencies` version `2021.0.7`, everything works fine. But if you upgrade `configuration-client` to `2021.0.8`, and run it again, you'll see that:
* There is a few seconds of waiting when the app starts, because the new code is trying to connect to `local.zookeeper.invalid`
* The log lines written (to `System.out` for simplicity) by the `My*` classes only start after the Spring logo
* Spring starts printing a lot of errors, e.g. `Error fetching config server instance from Zookeeper` and `Unable to resolve address: local.zookeeper.invalid/<unresolved>:2181`
* The `/message` REST API results in `No message`

**Comment by spencergibb** [comment]
Thanks @pantherdd for taking the time to make the reproducer!

**Comment by ryanjbaxter** [comment]
Agree it was super helpful!

**Comment by pantherdd** [comment]
And thanks to you both for the quick fix. :)

However I'm a bit confused with regards to versions. The changes were merged today, and the target milestone is set as `3.1.5`, but that seems to have been released yesterday without this:
* https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies/2021.0.9
* https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-zookeeper-dependencies/3.1.5
* https://github.com/spring-cloud/spring-cloud-zookeeper/compare/v3.1.4...v3.1.5
* https://spring.io/blog/2023/12/20/spring-cloud-2021-0-9-aka-jubilee-is-now-available/

Can you clarify? Thanks 🙇‍♂️

**Comment by ryanjbaxter** [comment]
That was my mistake it should have been 4.0.5

**Comment by pantherdd** [comment]
Ah, I see. Is there a plan to backport this to `3.1.x` too, given that it's a bug fix for a regression in the penultimate release? Or if that's not possible because the solution in #325 is dependent on something new in Spring 6 / Boot 3 / Cloud 4, what are our options (assuming we can't upgrade everything to the new major versions just yet)?

**Comment by ryanjbaxter** [comment]
The 3.1.x branch is no longer under open source support.  We did the final release yesterday (even though it was no longer supported) because we had enough fixes in various projects across the 2021.0.x release train to warrant doing a release for a number of projects.  At this point it is recommended that you begin to upgrade to 2022.0.x or 2023.0.x.

**Comment by pantherdd** [comment]
Understood, and that is of course in our plans.

Given the above, the only alternatives I see right now for projects that are affected by this bug and that still use the `2021.0.x` release train, is to either stay on the last working version which is `2021.0.7` (or more specifically Spring Cloud Zookeeper `3.1.3`), or to implement some local workaround for the regression (e.g. by overriding the `ConfigServerInstanceProvider.Function` bean). None of these are ideal, but given that this release train is now frozen, there should at least be no risk of missing out on improvements or incompatible changes breaking the workaround. Obviously, upgrading to the next major version is preferred.

**Comment by ryanjbaxter** [comment]
Correct.  And of course we could consider a release if there was a huge demand for a fix, but as of right now there is not

**Comment by pantherdd** [comment]
For the record, the final fix for this is in #328.
Some more context can be found in #325 and #327, but the code in them is superseded by #328.
