### ISSUE TITLE
Upgrade curator framework to 5.7.1

### ISSUE THREAD

**Issue by lambliesdown** [spring-cloud/spring-cloud-zookeeper#330]
**Is your feature request related to a problem? Please describe.**
spring-cloud-zookeeper-dependencies refers to curator.version 5.1.0 which is from 2020 and exhibits multiple vulnerabilities
(see https://mvnrepository.com/artifact/org.apache.curator/curator-framework/5.1.0).
Our security scanning constantly lists those in projects using spring-cloud-zookeeper.

**Describe the solution you'd like**
Any chance to update to the latest curator-framework 5.6.0 in the next major spring-cloud version?

**Comment by spencergibb** [comment]
We can do it in a minor. Development on 4.2.0 will start after May 2024

**Comment by lambliesdown** [comment]
Any update on this? In https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-zookeeper-dependencies/4.2.0-M1 I'm still seeing
<curator.version>5.1.0</curator.version>

**Comment by spencergibb** [comment]
It is still todo
