### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by breun** [spring-cloud/spring-cloud-zookeeper#333]
On https://spring.io/projects/spring-cloud-zookeeper#learn there are some broken links:

* 4.1.2 links to https://docs.spring.io/spring-cloud-zookeeper/docs/current/reference/html/, but the documentation for 4.1.2 seems to live at https://docs.spring.io/spring-cloud-zookeeper/reference/4.1.2
* 4.1.3-SNAPSHOT links to https://docs.spring.io/spring-cloud-zookeeper/docs/4.1.3-SNAPSHOT/reference/html/, which returns 404 Not Found.

For 4.1.x the correct URL format seems to be https://docs.spring.io/spring-cloud-zookeeper/reference/${version}, because these work:

* 4.1.2: https://docs.spring.io/spring-cloud-zookeeper/reference/4.1.2
* 4.1.3-SNAPSHOT: https://docs.spring.io/spring-cloud-zookeeper/reference/4.1.3-SNAPSHOT

**Comment by ryanjbaxter** [comment]
Once the site is updated in a few minutes it should be fixed
