### ISSUE TITLE
Examples for service discovery and registration?

### ISSUE THREAD

**Issue by efenderbosch** [spring-cloud/spring-cloud-zookeeper#34]
The sample app doesn't perform these operations. I'm stumbling around the ZookeeperServiceDiscovery class, but this isn't obvious how to proceed.

**Comment by spencergibb** [comment]
It does.  [This line](https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-sample/src/main/java/org/springframework/cloud/zookeeper/sample/SampleZookeeperApplication.java#L40) does the registration.  [This line](https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-sample/src/main/java/org/springframework/cloud/zookeeper/sample/SampleZookeeperApplication.java#L63) shows the use of the `LoadBalancerClient`.  You can also use [`RestTemplate`](http://projects.spring.io/spring-cloud/spring-cloud.html#_spring_resttemplate_as_a_load_balancer_client) and [`Feign`](http://projects.spring.io/spring-cloud/spring-cloud.html#spring-cloud-feign) as load balancer clients.

**Comment by efenderbosch** [comment]
Ahhh, ok. It is asking for an instance of itself. I get it now. Thanks.
