### ISSUE TITLE
In config resolver placeholders doesn't work

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-zookeeper#35]
Unable to reference other properties as normal spring boot config, ie `${sever.port}`.

**Comment by marcingrzejszczak** [comment]
You mean that this:

```
@Value("${server.port}") Integer port
```

doesn't work?

**Comment by spencergibb** [comment]
No, if you put `${server.port}` in a configuration item in zookeeper, it doesn't get resolved.

**Comment by spencergibb** [comment]
In consul they just worked, I'm going to close this.
