### ISSUE TITLE
Configuration to change connectString

### ISSUE THREAD

**Issue by sigrist** [spring-cloud/spring-cloud-zookeeper#44]
I'm trying to change the default connectString but is not working. This is my application.properties
```
spring.cloud.zookeeper.enabled = true
spring.cloud.zookeeper.connectString = 192.168.40.82:2181
zookeeper.connectString = 192.168.40.82:2181
```

But the class ZookeeperProperties does not load the properties.
Related to #35 ?

**Comment by marcingrzejszczak** [comment]
Try to pass those in `bootstrap.poperties`

**Comment by sigrist** [comment]
Worked!

Thanks!

**Comment by rnavarropiris** [comment]
can you please point to a documentation of how this `bootstrap.yml` file is interpreted & how can their values be overwritten (similar to the [External configuration docu](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html))? I can't find it anywhere...

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/docs/src/main/asciidoc/spring-cloud-zookeeper.adoc#registering-with-zookeeper
