### ISSUE TITLE
Discovery does not recognise new instances or removed instances

### ISSUE THREAD

**Issue by sigrist** [spring-cloud/spring-cloud-zookeeper#45]
Hi all,

I'm starting to use Zookeeper for service discovery with Spring Cloud. I created a simple application to demonstrate my issue. My client does not recognise when new instances are available or, even worse, when an instance is not available. The code for this example is https://github.com/sigrist/zookeeper-sandbox

I created a simple HTTP service that sends a Hello. I build a client service that uses this 'Hello Service'. If I started 2 or more services *before* the client, I can see that the load balancer works as expected, calling all the available instances. But if I shutdown one of the servers, the client still tries to connect to it, failing and showing the Default value for a failed request (using Netflix Hystrix).

If I started new server instances, the client does not recognise then, using only the available at boot time.

When I started new servers, I can see in the Client log that a new instance is available, but the server list is not updated:
```
2015-11-02 12:36:36.314  INFO 35764 --- [-ServiceCache-0] .w.DependencyStateChangeListenerRegistry : Service cache state change for '/zookeeper-sandbox' instances, current service state: CONNECTED
```

Also, when I shutdown one server instance, a log in the client shows a new event:
```
2015-11-02 12:37:29.646  INFO 35764 --- [-ServiceCache-0] .w.DependencyStateChangeListenerRegistry : Service cache state change for '/zookeeper-sandbox' instances, current service state: CONNECTED
```

My question is, how to update the server list in the client? Is there some configuration that I'm missing?

Thanks
Sigrist

**Comment by spencergibb** [comment]
I haven't tried your project yet, but the sample recognizes new and removed instances.

**Comment by spencergibb** [comment]
So the issue is that `DependenciesBasedLoadBalancer` does not extend `DynamicServerListLoadBalancer`, just `BaseLoadBalancer` which doesn't update the list. The workaround is to not use the dependencies for now. /cc @marcingrzejszczak

**Comment by spencergibb** [comment]
Thanks @sigrist for the report and @marcingrzejszczak for the fix!
