### ISSUE TITLE
DependenciesBasedLoadBalancer seems to be picked by any RestTemplate

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-zookeeper#53]
Only @LoadBalanced one should be using that LoadBalancer

**Comment by spencergibb** [comment]
We've always taken the approach of a `@LoadBalanced` `RestTemplate` and one that's not.

**Comment by marcingrzejszczak** [comment]
To consider:

```
 @Autowired @LoadBalanced RestTemplate loadBalancedRestTemplate;

    @Bean
    public RestTemplateCustomizer restTemplateCustomizerForRibbon(
            final LoadBalancerInterceptor loadBalancerInterceptor) {
        return new RestTemplateCustomizer() {
            @Override
            public void customize(RestTemplate restTemplate) {
                if (loadBalancedRestTemplate == restTemplate) {
                    List<ClientHttpRequestInterceptor> list = new ArrayList<>();
                    list.add(loadBalancerInterceptor);
                    restTemplate.setInterceptors(list);
                }
            }
        };
    }
```

**Comment by spencergibb** [comment]
I would add to existing interceptors rather than _set_ them, but something like that.

**Comment by spencergibb** [comment]
This doesn't make much sense to me as I'm trying to go back and understand the problem. When `DependenciesBasedLoadBalancer` is created by `ZookeeperRibbonClientConfiguration`, it becomes the default loadbalancer for ribbon. All `RestTemplate`s that have the `LoadBalancerInterceptor` will use that load balancer. Not sure what we can do here. What is the scenario where this is a problem?

**Comment by marcingrzejszczak** [comment]
Since it's been a couple of months I think what I meant the problem was is that we had somewhere in the codebase injection of `List<ClientHttpRequestInterceptor> interceptors`. We did some custom logic there on those interceptors and one of those interceptors was the LoadBalanced one and everything blew up ;) I'm closing it cause it doesn't matter anymore.
