### ISSUE TITLE
Implement ServiceInstance.getMetadata

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-zookeeper#57]
New from https://github.com/spring-cloud/spring-cloud-commons/pull/56

**Comment by tkvangorder** [comment]
Until this enhancement has been completed, what is the recommended way to get access to the meta-data? We are using Eureka so we don't have to have a generalized solution, we just need access to the meta-data.

**Comment by spencergibb** [comment]
@tkvangorder this is for spring-cloud-zookeeper. spring-cloud-netflix already implements this.

**Comment by tkvangorder** [comment]
Sorry, I should look closer at the issue details, I was reviewing https://github.com/spring-cloud/spring-cloud-netflix/issues/419 but I missed the commit. https://github.com/spring-cloud/spring-cloud-netflix/commit/03f6d12e5087ad93c0e35864255e8c7475723f7a


I'm not using the latest version yet, so I will just cast the service Instances into Eureka instances until we upgrade. (not pretty, but only temporary)  Thanks for the help.

**Comment by orevial** [comment]
@spencergibb what is the point of implementing ServiceInstance.getMetadata here ? It seems to me that it is not really used except in discovery client, but when registering instances to Zookeeper the ServiceInstance class used is the one from Curator... shouldn't we consider a way to register a ServiceInstance with a custom payload instead ? Being able to customize the payload would be cool, i.e. not giving `ServiceInstance<ZookeeperInstance>` but `ServiceInstance<ZookeeperInstanceInterface> `or such ?!
