### ISSUE TITLE
Update to Curator 2.9.1

### ISSUE THREAD

**Issue by tietang** [spring-cloud/spring-cloud-zookeeper#59]
Apache Curator 2.8.0 may make CPU load 10%-20%, please update version to 2.9.1

see as follows: http://mail-archives.apache.org/mod_mbox/curator-user/201502.mbox/%3C58541717BBD8834B8AA650F21087592211C848@JTCLPSWEXMBH04.lpsvcs.com%3E
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12314425&version=12332392
https://issues.apache.org/jira/browse/CURATOR-228

**Comment by dsyer** [comment]
I tested this quickly with just the tests in spring-cloud-zookeeper and it seems to work. Any objections from anyone else ( @spencergibb @marcingrzejszczak @pperalta ?)

**Comment by tietang** [comment]
I tested it in Mac osx/CentOS7/CentOS6/alios6(2.6.32-220.23.2.al.ali1.1.alios6.x86_64 ),

in Mac osx/CentOS7/CentOS6 can't be found this issue, but in alios6(2.6.32-220.23.2.al.ali1.1.alios6.x86_64 ) has, may related with OS.

**Comment by marcingrzejszczak** [comment]
LGTM
