### ISSUE TITLE
DependencyEnvironmentPostProcessor is broken

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-zookeeper#64]
With one of the releases of Spring Boot AFAIR `spring.application.name` gets resolved to `default`

**Comment by spencergibb** [comment]
probably an ordering issue.

**Comment by marcingrzejszczak** [comment]
Most likely so - I don't think we have a test for that :scream: ...

**Comment by spencergibb** [comment]
I don't think this is a problem with `DependencyEnvironmentPostProcessor`. It wouldn't cause `spring.application.name` to resolve to `default`. Where did you see this?

**Comment by marcingrzejszczak** [comment]
It's no longer broken. I've confirmed it.
