### ISSUE TITLE
Using ".dependencies." infix as a part of property

### ISSUE THREAD

**Issue by cameleeck** [spring-cloud/spring-cloud-zookeeper#70]
Due to cloud-zookeeper uses ".dependencies." in some of properties e.g. `spring.cloud.zookeeper.dependencies.ribbon.enabled` during auto-configuration when property is set `org.springframework.cloud.zookeeper.discovery.dependency.ZookeeperDependencies` field dependecies is polluted by w this property. That may lead to wrong behaviors.

**Comment by marcingrzejszczak** [comment]
Fixed in https://github.com/cameleeck/spring-cloud-zookeeper/commit/84b3f5d32345a2bb385b8cb191b6910547a97dcf
