### ISSUE TITLE
Can not build project  from the sources

### ISSUE THREAD

**Issue by vadimkim** [spring-cloud/spring-cloud-zookeeper#78]
Local Zookeeper instance is running with default settings, but discovery tests are failed.

Executed: mvn --settings .settings.xml package

Result: 
Tests run: 39, Failures: 0, Errors: 21, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] spring-cloud-zookeeper-dependencies ................ SUCCESS [  0.002 s]
[INFO] Spring Cloud Zookeeper ............................. SUCCESS [  1.785 s]
[INFO] Spring Cloud Zookeeper Core ........................ SUCCESS [  5.670 s]
[INFO] Spring Cloud Zookeeper Config ...................... SUCCESS [  8.787 s]
[INFO] Spring Cloud Zookeeper Discovery ................... FAILURE [  3.618 s]
[INFO] Spring Cloud Starter Zookeeper ..................... SKIPPED
[INFO] Spring Cloud Starter Zookeeper Config .............. SKIPPED
[INFO] Spring Cloud Starter Zookeeper Discovery ........... SKIPPED
[INFO] Spring Cloud Starter Zookeeper All ................. SKIPPED
[INFO] Spring Cloud Zookeeper Sample ...................... SKIPPED
[INFO] Spring Cloud Zookeeper Docs ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.559 s
[INFO] Finished at: 2016-04-30T10:29:05+03:00
[INFO] Final Memory: 61M/425M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.6:test (default-test) on project spring-cloud-zookeeper-discovery: There are test failures.
[ERROR]

**Comment by marcingrzejszczak** [comment]
So maybe one of the tests is using the default Zookeeper port. Disable the
local Zookeeper and try again.

Can you provide the name of the broken test?

**Comment by vadimkim** [comment]
It seems there is no difference whether local Zookeeper is running on not. I got the same error, but tracing back to the first one gives:

10:52:44,144 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(/var/log/mspspring.log,true) call failed. java.io.FileNotFoundException: /var/log/mspspring.log (Permission denied)
        at java.io.FileNotFoundException: /var/log/mspspring.log (Permission denied)

I am building the library under user account. Will try to switch to root and build again.

**Comment by vadimkim** [comment]
Under root account build was successful.  This is strange requirement, but you should mention it at your building guide.

**Comment by marcingrzejszczak** [comment]
Hmm I think that you have wrong user rights setup and it has nothing to do
with our build requirements

**Comment by vadimkim** [comment]
I'd argue about my user setup rights, because they are standard to Debian and I am almost sure -- for all UNIX systems. Non-privilege user shouldn't have write permission at /var/log folder because it is meant for system log-files, not user one. I think you should pay attention to security issues.

**Comment by marcingrzejszczak** [comment]
I assure you that I have executed the builds on standard installations of Ubuntu, Mac OS and the build was ran successfully also on Travis, Bamboo and our Jenkins instances. Never did we have such issues as you're mentioning.

**Comment by marcingrzejszczak** [comment]
Are you sure that those errors with the logs broke the build or was there any other reason for that?

**Comment by vadimkim** [comment]
I have looked deeper and didn't see other error than that 
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(/var/log/mspspring.log,true) call failed. java.io.FileNotFoundException: /var/log/mspspring.log (Permission denied)

This causes SpringApplication context initialization failure and entire Spring application is failed to start. That is why tests are failed.   

I am using KUbuntu 14.04 LTS and JDK build 1.8.0_92-b14.
