### ISSUE TITLE
When the network does not stability, the spring Cloud app will try to refresh

### ISSUE THREAD

**Issue by tietang** [spring-cloud/spring-cloud-zookeeper#82]
When the network does not stability, the spring Cloud app will try to refresh.

**Comment by marcingrzejszczak** [comment]
Thanks for the issue but I completely don't know what to do about it :P Can you provide more details? A sample app? I mean anything... :P The app tries to refresh what? What does it mean "network does not stability" ?

**Comment by marcingrzejszczak** [comment]
ping?

**Comment by tietang** [comment]
I have fixed it. The new spring-cloud-zookeeper version take a new refreshable feature（spring.cloud.zookeeper.config.watcher.enabled）, and my project have a refreshable zk node data feture, them have conflict.

**Comment by tietang** [comment]
tks

**Comment by tietang** [comment]
I have fixed it. The new spring-cloud-zookeeper version take a new refreshable feature（spring.cloud.zookeeper.config.watcher.enabled）, and my project have a refreshable zk node data feture, them have conflict. tks.
