### ISSUE TITLE
About doc Run sample

### ISSUE THREAD

**Issue by yyq2013** [spring-cloud/spring-cloud-zookeeper#83]
In step7, the server port is change from 8080 to 8081, why step8 still access 8080 and the server responses the 8081 in content? I missing anything?

**Comment by marcingrzejszczak** [comment]
The idea is to show that Zookeeper works as a Service Discovery and that you can see the instances switched in a round robin fashion. To do that you need to applications ran simultaneously and registered in Zookeeper.

**Comment by yyq2013** [comment]
Thanks @marcingrzejszczak to point it, I understand you, I shutdown the first application.

**Comment by marcingrzejszczak** [comment]
Np!
