### ISSUE TITLE
Work service discovery if setWebEnvironment(false)

### ISSUE THREAD

**Issue by skobets** [spring-cloud/spring-cloud-zookeeper#91]
Hello, there is the following situation:
There is a class annotated `@FeignClient` It is located in its own project

```
package test;


@FeignClient(serviceId = "attributes-dictionary")
public interface ProfileAttributeDictionaryClient {

    @RequestMapping("/{language}")
    String findAll(@PathVariable("language") String language);

}
```

There is another project that will import this class

```
@SpringBootApplication
@EnableDiscoveryClient
@EnableFeignClients(Array("test"))
class Configuration {
  @LoadBalanced
  @Bean
  def restTmp(): RestTemplate = {
    new RestTemplate()
  }
  @Bean
  def job: Job = new Job
}
```

```
class Job {
  @Autowired
  var client: ProfileAttributeDictionaryClient = _

  def execute(): Unit = {
    val split: Array[String] =  client.findAll("en").split(System.lineSeparator())
    print(split)
```

```
object Application extends App {
  val application: SpringApplication = new SpringApplication(classOf[Configuration])
  application.setWebEnvironment(false)
  val context: ConfigurableApplicationContext = application.run()
  context.getBean(classOf[Job]).execute()
}
```

```
spring:
  application:
    name: test-job
  cloud:
    config:
        enabled: false
    circuit:
      breaker:
        enabled: false
    zookeeper:
      enabled: true
      connect-string: localhost:2181
      discovery:
        enabled: true
        register: false
      dependencies:
        attributes-dictionary:
          path: attributes-dictionary
hystrix:
  metrics:
    enabled: false
```

**if setWebEnvironment is true -> everything works fine
if setWebEnvironment is false a list of servers to be null**

```
Exception in thread "main" com.netflix.hystrix.exception.HystrixRuntimeException: findAll failed and no fallback available.
….
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.loadbalancer.ILoadBalancer]: Factory method 'dependenciesBasedLoadBalancer' threw exception; nested exception is java.lang.NullPointerException
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
    ... 48 more
Caused by: java.lang.NullPointerException
    at org.springframework.cloud.zookeeper.discovery.ZookeeperServerList.getServers(ZookeeperServerList.java:80)
    at org.springframework.cloud.zookeeper.discovery.ZookeeperServerList.getInitialListOfServers(ZookeeperServerList.java:68)
```

Is there a way to automatically configure, in the case setWebEnvironment(false) ?

**Comment by sekhrivijay** [comment]
I am facing the same issue in the following code. 
If i set .web(false) to false then it give an NPE 

`@SpringBootApplication
@EnableDiscoveryClient
public class HelloClient implements CommandLineRunner {
    @LoadBalanced
    @Bean
    RestTemplate restTemplate() {
        return new RestTemplate();
    }

    @Autowired
    DiscoveryClient discoveryClient;

    @Autowired
    private RestTemplate restTemplate;

    public static void main(String[] args) {
        new SpringApplicationBuilder(HelloClient.class)
//                .web(false)
                .run(args);
    }

    @Override
    public void run(String... strings) throws Exception {
        Map<String, String> params = new HashMap<>();
        params.put("name", "hahahahhh");
        discoveryClient.getServices()
                .forEach(System.out::println);
        List<ServiceInstance> list = discoveryClient.getInstances("hello-world");
        System.out.println(list);
        Saying saying = this.restTemplate.getForObject("http://hello-world/", Saying.class, params);
        System.out.println(saying);


    }
}`

**Comment by jwdevs** [comment]
Hello,

The same for me. Unable to use zookeeper discovery if the app is started without the web context due to this NPE. Any idea of when this will be handled? 

Cheers,
Jakub

**Comment by marcingrzejszczak** [comment]
I'm on it ;)

**Comment by jwdevs** [comment]
Thanks a lot for your help Marcin!
