### ISSUE TITLE
Add the capability of starting an application if Zookeeper is not running (at least for Dynamic Configuration purposes)

### ISSUE THREAD

**Issue by erecarte** [spring-cloud/spring-cloud-zookeeper#97]
In order to make applications more resilient, I think it would be good for the app to start or at least add the capability of doing so with a runtime property (probably disabled by default) when Zookeeper is not running.
My proposal is that when Zookeeper is down, the app sets a connection listener and starts anyway. When the connection is re-established, then the property source is hooked in and a refresh event is published.

**Comment by spencergibb** [comment]
spring-cloud-consul does two things now:

1. it uses spring-retry to retry connections
2. it has a failFast property, that when set to false will continue to run disregarding the failure to connect to consul

Something similar here could be useful as well.

Your proposal is interesting, though it is out of scope for the title of the issue.

**Comment by erecarte** [comment]
Thanks @spencergibb. How do you mean out of scope for the title? Should I change it?

**Comment by spencergibb** [comment]
Your proposal
> My proposal is that when Zookeeper is down, the app sets a connection listener and starts anyway. When the connection is re-established, then the property source is hooked in and a refresh event is published.

is separate from just letting the app start if zookeeper isn't there. It's another feature.

**Comment by erecarte** [comment]
Hi @spencergibb looking at your previous comment about spring-cloud-consul...Curator already has the retry mechanism built in, right? do you think it would be better to leave it that way or still go with the spring-retry mechanism?

**Comment by spencergibb** [comment]
No, use the built in retry, which is what eureka does. I'd forgotten about that.

**Comment by erecarte** [comment]
Hey! it looks like it's a simple change since the refreshing when the connection is established is already done apparently. So it would just be a matter of adding the `spring.cloud.zookeeper.config.failFast` property.
I have it working, but I can't seem to test it properly without having to wait for the Curator client to give up, which takes quite a bit of time. Do you know how can I override the `RetryPolicy` bean so it doesn't wait for so long? I can't seem to do so because I think it's in a different context (bootstrap) from my test? This is what my test looks like:

```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = ZookeeperPropertySourceLocatorFailFastTests.Config.class, webEnvironment = NONE, properties = {
   "spring.application.name=testZookeeperPropertySourceLocatorFailFast",
   "spring.cloud.zookeeper.config.connectString=localhost:2188",
   "spring.cloud.zookeeper.config.failFast=false"
})
public class ZookeeperPropertySourceLocatorFailFastTests {
   @Configuration
   public static class Config {
      @Primary
      @Bean
      public RetryPolicy retryPolicy() {
         return new RetryOneTime(10);
      }
   }

   @Test
   public void testFailFastFalse() {
   }
}
```

**Comment by spencergibb** [comment]
Adding a bean of `RetryPolicy` should do it

**Comment by erecarte** [comment]
That's what I'm doing in my example? If I put a breakpoint in the `retryPolicy` it's never triggered, and with the new `failFast` functionality it's triggered after Curator has already done the retry logic. Isn't it because the Spring Cloud Config stuff happens in the `bootstrap` context?

**Comment by spencergibb** [comment]
@erecarte yes. You'd need to add a test bootstrap configuration similar to https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-config/src/main/resources/META-INF/spring.factories#L6-L7
