### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by zhuxiang1985** [spring-cloud/spring-cloud-zookeeper#99]
when I use the command 'mvn --settings .settings.xml package' , then throw the 'org.apache.maven.InternalErrorException: Internal error: org.apache.maven.artifact.InvalidArtifactRTException: For artifact {org.springframework:spring-core:null:jar}: The version cannot be empty.' . Please tell me how to fix it?

**Comment by spencergibb** [comment]
We usually use `./mvnw` (the maven wrapper). What version of maven are your using?

**Comment by spencergibb** [comment]
Instructions for building in the readme

**Comment by zhuxiang1985** [comment]
maven version is 3.1.1

**Comment by spencergibb** [comment]
We require maven 3.3.x

**Comment by zhuxiang1985** [comment]
ok，I will try it.
